<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/includes/auth.php';
require_once dirname(__DIR__) . '/includes/csrf.php';
require_once __DIR__ . '/layout.php';
require_once dirname(__DIR__) . '/services/attendance.php';

$current = tuman_require_role('TEACHER'); $error = null; $students = [];
try { $students = array_filter(tuman_teacher_students(tuman_database(), $current['id']), static fn(array $student): bool => $student['assignment_status'] === 'ACTIVE'); } catch (Throwable $exception) { error_log('Tuman attendance student selection failed: ' . $exception->getMessage()); $error = 'Students cannot be loaded right now.'; }
$values = ['assignment_id' => '', 'session_date' => gmdate('Y-m-d'), 'status' => 'PRESENT', 'start_time' => '', 'end_time' => '', 'remarks' => ''];
if ($_SERVER['REQUEST_METHOD'] === 'POST') { foreach ($values as $key => $value) { $values[$key] = trim((string) ($_POST[$key] ?? '')); } if (!tuman_csrf_is_valid($_POST['csrf_token'] ?? null)) { $error = 'Your request could not be verified. Please try again.'; } else { try { tuman_create_attendance(tuman_database(), $current['id'], tuman_teacher_assignment_id($values['assignment_id']), $values); header('Location: /Tuman/teacher/attendance.php?created=1'); exit; } catch (InvalidArgumentException $exception) { $error = $exception->getMessage(); } catch (Throwable $exception) { error_log('Tuman attendance creation failed: ' . $exception->getMessage()); $error = 'Unable to save attendance right now.'; } } }
tuman_teacher_page_start('Record attendance');
?>
<h1>Record attendance</h1><p>Times are required only for a present session. Duration is calculated automatically.</p><?php if ($error): ?><p role="alert"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p><?php endif; ?><?php if ($students === []): ?><p>You need an active student before recording attendance.</p><?php else: ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(), ENT_QUOTES, 'UTF-8') ?>"><p><label>Student <select name="assignment_id" required><option value="">Choose student</option><?php foreach ($students as $student): ?><option value="<?= (int) $student['assignment_id'] ?>"<?= (string) $student['assignment_id'] === $values['assignment_id'] ? ' selected' : '' ?>><?= htmlspecialchars(trim($student['first_name'] . ' ' . ($student['last_name'] ?? '')), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><label>Session date <input type="date" name="session_date" required value="<?= htmlspecialchars($values['session_date'], ENT_QUOTES, 'UTF-8') ?>"></label></p><p><label>Status <select name="status"><?php foreach (TUMAN_ATTENDANCE_STATUSES as $status): ?><option value="<?= $status ?>"<?= $status === $values['status'] ? ' selected' : '' ?>><?= $status ?></option><?php endforeach; ?></select></label></p><p><label>Start time <input type="time" name="start_time" value="<?= htmlspecialchars($values['start_time'], ENT_QUOTES, 'UTF-8') ?>"></label></p><p><label>End time <input type="time" name="end_time" value="<?= htmlspecialchars($values['end_time'], ENT_QUOTES, 'UTF-8') ?>"></label></p><p><label>Remarks <textarea name="remarks" maxlength="500" rows="4"><?= htmlspecialchars($values['remarks'], ENT_QUOTES, 'UTF-8') ?></textarea></label></p><p><button type="submit">Save attendance</button> <a href="/Tuman/teacher/attendance.php">Cancel</a></p></form><?php endif; tuman_teacher_page_end(); ?>
