<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/includes/auth.php';
require_once __DIR__ . '/layout.php';
require_once dirname(__DIR__) . '/services/billing.php';

$current = tuman_require_role('TEACHER'); $error = null; $rules = []; $students = []; $assignmentId = null;
try { $database = tuman_database(); $students = tuman_teacher_students($database, $current['id']); if (isset($_GET['assignment_id']) && $_GET['assignment_id'] !== '') { $assignmentId = tuman_teacher_assignment_id($_GET['assignment_id']); if (tuman_teacher_student($database, $current['id'], $assignmentId) === null) { throw new InvalidArgumentException(); } } $rules = tuman_teacher_billing_rules($database, $current['id'], $assignmentId); } catch (InvalidArgumentException $exception) { http_response_code(404); exit('Billing unavailable.'); } catch (Throwable $exception) { error_log('Tuman billing list failed: ' . $exception->getMessage()); $error = 'Billing rules cannot be loaded right now.'; }
tuman_teacher_page_start('Billing rules');
?>
<h1>Billing rules</h1><p>Set effective-dated hourly or monthly rates for your students.</p><form method="get"><p><label>Student <select name="assignment_id"><option value="">All my students</option><?php foreach ($students as $student): ?><option value="<?= (int) $student['assignment_id'] ?>"<?= $assignmentId === (int) $student['assignment_id'] ? ' selected' : '' ?>><?= htmlspecialchars(trim($student['first_name'] . ' ' . ($student['last_name'] ?? '')), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label> <button type="submit">View</button></p></form><p><a class="button" href="/Tuman/teacher/billing-create.php">Add billing rule</a></p><?php if ($error): ?><p role="alert"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p><?php else: ?><div style="overflow-x:auto"><table><thead><tr><th>Student</th><th>Rule</th><th>Mode</th><th>Rate</th><th>Status</th><th>Effective dates</th><th>Actions</th></tr></thead><tbody><?php foreach ($rules as $rule): ?><tr><td><?= htmlspecialchars(trim($rule['first_name'] . ' ' . ($rule['last_name'] ?? '')), ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($rule['rule_name'] ?? ('Rule #'.$rule['id']), ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($rule['billing_mode'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars(tuman_billing_rate_label($rule['rate'], $rule['billing_mode']), ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($rule['status'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($rule['effective_from'] . ($rule['effective_to'] ? ' to ' . $rule['effective_to'] : ''), ENT_QUOTES, 'UTF-8') ?></td><td><a href="/Tuman/teacher/billing-edit.php?id=<?= (int) $rule['id'] ?>">Edit</a><?php if ($rule['status'] === 'ACTIVE'): ?> · <a href="/Tuman/teacher/billing-status.php?id=<?= (int) $rule['id'] ?>">End</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; tuman_teacher_page_end(); ?>
