<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php'; require_once dirname(__DIR__) . '/includes/csrf.php'; require_once __DIR__ . '/layout.php'; require_once dirname(__DIR__) . '/services/billing.php';
$current=tuman_require_role('TEACHER'); $id=filter_var($_GET['id']??$_POST['id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]); if(!$id){http_response_code(404);exit('Billing unavailable.');}$record=tuman_teacher_billing_rule(tuman_database(),$current['id'],(int)$id);if($record===null){http_response_code(404);exit('Billing unavailable.');}$error=null;$values=['rule_name'=>$record['rule_name']??('Rule #'.$record['id']),'billing_mode'=>$record['billing_mode'],'rate'=>$record['rate'],'currency_code'=>$record['currency_code']??'INR','effective_from'=>$record['effective_from'],'effective_to'=>$record['effective_to']??''];
if($_SERVER['REQUEST_METHOD']==='POST'){foreach($values as $key=>$value){$values[$key]=trim((string)($_POST[$key]??''));}if(!tuman_csrf_is_valid($_POST['csrf_token']??null)){$error='Your request could not be verified. Please try again.';}else{try{tuman_update_billing_rule(tuman_database(),$current['id'],(int)$id,$values);header('Location: /Tuman/teacher/billing.php?updated=1');exit;}catch(InvalidArgumentException $e){$error=$e->getMessage();}catch(Throwable $e){error_log($e->getMessage());$error='Unable to update the billing rule right now.';}}}
tuman_teacher_page_start('Edit billing rule');
?>
<h1>Edit billing rule</h1><p>Changes do not alter existing invoices or payments.</p><?php if($error): ?><p role="alert"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= (int)$id ?>"><p><label>Rule name <input name="rule_name" maxlength="100" required value="<?= htmlspecialchars($values['rule_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Billing mode <select name="billing_mode"><?php foreach(TUMAN_BILLING_MODES as $mode): ?><option value="<?= $mode ?>"<?= $mode===$values['billing_mode']?' selected':'' ?>><?= $mode==='HOURLY'?'Hourly':'Fixed monthly' ?></option><?php endforeach; ?></select></label></p><p><label>Currency <select name="currency_code"><?php foreach(TUMAN_CURRENCIES as $code=>$name): ?><option value="<?= $code ?>"<?= $code===$values['currency_code']?' selected':'' ?>><?= htmlspecialchars($code.' — '.$name,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><label>Rate <input name="rate" required value="<?= htmlspecialchars($values['rate'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Effective from <input type="date" name="effective_from" required value="<?= htmlspecialchars($values['effective_from'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Effective to <input type="date" name="effective_to" value="<?= htmlspecialchars($values['effective_to'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><button>Save changes</button> <a href="/Tuman/teacher/billing.php">Cancel</a></p></form>
<?php tuman_teacher_page_end(); ?>
