<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php'; require_once dirname(__DIR__) . '/includes/csrf.php'; require_once __DIR__ . '/layout.php'; require_once dirname(__DIR__) . '/services/billing.php';
$current=tuman_require_role('TEACHER'); $error=null; $students=[];
try { $students=array_filter(tuman_teacher_students(tuman_database(),$current['id']),static fn(array $s):bool=>$s['assignment_status']==='ACTIVE'); } catch(Throwable $e) { $error='Students cannot be loaded right now.'; }
$values=['assignment_id'=>'','billing_mode'=>'HOURLY','rate'=>'','currency_code'=>'INR','effective_from'=>gmdate('Y-m-d'),'effective_to'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){foreach($values as $key=>$value){$values[$key]=trim((string)($_POST[$key]??''));} if(!tuman_csrf_is_valid($_POST['csrf_token']??null)){$error='Your request could not be verified. Please try again.';}else{try{tuman_create_billing_rule(tuman_database(),$current['id'],tuman_teacher_assignment_id($values['assignment_id']),$values);header('Location: /Tuman/teacher/billing.php?created=1');exit;}catch(InvalidArgumentException $e){$error=$e->getMessage();}catch(Throwable $e){error_log($e->getMessage());$error='Unable to save the billing rule right now.';}}}
tuman_teacher_page_start('Add billing rule');
?>
<h1>Add billing rule</h1><?php if($error): ?><p role="alert"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><p><label>Student <select name="assignment_id" required><option value="">Choose student</option><?php foreach($students as $s): ?><option value="<?= (int)$s['assignment_id'] ?>"<?= (string)$s['assignment_id']===$values['assignment_id']?' selected':'' ?>><?= htmlspecialchars(trim($s['first_name'].' '.($s['last_name']??'')),ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><label>Billing mode <select name="billing_mode"><?php foreach(TUMAN_BILLING_MODES as $mode): ?><option value="<?= $mode ?>"<?= $mode===$values['billing_mode']?' selected':'' ?>><?= $mode==='HOURLY'?'Hourly':'Fixed monthly' ?></option><?php endforeach; ?></select></label></p><p><label>Currency <select name="currency_code"><?php foreach(TUMAN_CURRENCIES as $code=>$name): ?><option value="<?= $code ?>"<?= $code===$values['currency_code']?' selected':'' ?>><?= htmlspecialchars($code.' — '.$name,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><label>Rate <input name="rate" inputmode="decimal" required value="<?= htmlspecialchars($values['rate'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Effective from <input type="date" name="effective_from" required value="<?= htmlspecialchars($values['effective_from'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Effective to <input type="date" name="effective_to" value="<?= htmlspecialchars($values['effective_to'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><button>Save billing rule</button> <a href="/Tuman/teacher/billing.php">Cancel</a></p></form>
<?php tuman_teacher_page_end(); ?>
