<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/includes/auth.php';
require_once __DIR__ . '/layout.php';
require_once dirname(__DIR__) . '/services/invoices.php';

$current = tuman_require_role('TEACHER'); $error = null; $invoices = []; $students = []; $assignmentId = null;
try { $database = tuman_database(); $students = tuman_teacher_students($database, $current['id']); if (isset($_GET['assignment_id']) && $_GET['assignment_id'] !== '') { $assignmentId = tuman_teacher_assignment_id($_GET['assignment_id']); if (tuman_teacher_student($database, $current['id'], $assignmentId) === null) { throw new InvalidArgumentException(); } } $invoices = tuman_teacher_invoices($database, $current['id'], $assignmentId); } catch (InvalidArgumentException $exception) { http_response_code(404); exit('Invoices unavailable.'); } catch (Throwable $exception) { error_log('Tuman invoice list failed: ' . $exception->getMessage()); $error = 'Invoices cannot be loaded right now.'; }
tuman_teacher_page_start('Invoices');
?>
<h1>Invoices</h1><p>Generate and manage your students’ monthly invoice snapshots.</p><form method="get"><p><label>Student <select name="assignment_id"><option value="">All my students</option><?php foreach ($students as $student): ?><option value="<?= (int) $student['assignment_id'] ?>"<?= $assignmentId === (int) $student['assignment_id'] ? ' selected' : '' ?>><?= htmlspecialchars(trim($student['first_name'] . ' ' . ($student['last_name'] ?? '')), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label> <button type="submit">View</button></p></form><p><a class="button" href="/Tuman/teacher/invoice-create.php">Generate draft invoice</a></p><?php if ($error): ?><p role="alert"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p><?php else: ?><div style="overflow-x:auto"><table><thead><tr><th>Invoice</th><th>Student</th><th>Billing month</th><th>Invoice date</th><th>Due date</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($invoices as $invoice): ?><tr><td><?= htmlspecialchars($invoice['invoice_number'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars(trim($invoice['first_name'] . ' ' . ($invoice['last_name'] ?? '')), ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars(substr($invoice['billing_period_from'], 0, 7), ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($invoice['invoice_date'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($invoice['due_date'] ?? '—', ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars(tuman_invoice_money_label($invoice['total_amount']), ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($invoice['status'], ENT_QUOTES, 'UTF-8') ?></td><td><a href="/Tuman/teacher/invoice-view.php?id=<?= (int) $invoice['id'] ?>">View</a><?php if ($invoice['status'] === 'DRAFT'): ?> · <a href="/Tuman/teacher/invoice-issue.php?id=<?= (int) $invoice['id'] ?>">Issue</a> · <a href="/Tuman/teacher/invoice-cancel.php?id=<?= (int) $invoice['id'] ?>">Cancel</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; tuman_teacher_page_end(); ?>
