<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php'; require_once dirname(__DIR__).'/includes/csrf.php'; require_once __DIR__.'/layout.php'; require_once dirname(__DIR__).'/services/invoices.php';
$current=tuman_require_role('TEACHER');$error=null;$students=array_filter(tuman_teacher_students(tuman_database(),$current['id']),fn($student)=>$student['assignment_status']==='ACTIVE');$values=['assignment_id'=>'','special_reason'=>'ADDITIONAL_CHARGES','comment'=>'','amount'=>'','currency_code'=>'INR','invoice_date'=>gmdate('Y-m-d'),'due_date'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){foreach($values as $key=>$value){$values[$key]=trim((string)($_POST[$key]??''));}if(!tuman_csrf_is_valid($_POST['csrf_token']??null)){$error='Your request could not be verified. Please try again.';}else{try{tuman_create_special_invoice(tuman_database(),$current['id'],tuman_teacher_assignment_id($values['assignment_id']),$values);header('Location: /Tuman/teacher/invoices.php?created=1');exit;}catch(InvalidArgumentException $exception){$error=$exception->getMessage();}catch(Throwable $exception){error_log('Tuman special invoice creation failed: '.$exception->getMessage());$error='Unable to create the special invoice right now.';}}}
tuman_teacher_page_start('Create special invoice');
?>
<h1>Create special invoice</h1><p>Use this for a one-off additional charge, compensation, or another explained reason.</p><?php if($error): ?><p role="alert"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><p><label>Student <select name="assignment_id" required><option value="">Choose student</option><?php foreach($students as $student): ?><option value="<?= (int)$student['assignment_id'] ?>"<?= $values['assignment_id']==$student['assignment_id']?' selected':'' ?>><?= htmlspecialchars(trim($student['first_name'].' '.($student['last_name']??'')),ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><label>Reason <select name="special_reason"><?php foreach(['ADDITIONAL_CHARGES'=>'Additional charges','COMPENSATION'=>'Compensation','OTHER'=>'Other reasons'] as $value=>$label): ?><option value="<?= $value ?>"<?= $values['special_reason']===$value?' selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label></p><p><label>Comment <textarea name="comment" required maxlength="500"><?= htmlspecialchars($values['comment'],ENT_QUOTES,'UTF-8') ?></textarea></label></p><p><label>Amount <input type="number" name="amount" min="0.01" step="0.01" required value="<?= htmlspecialchars($values['amount'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Currency <select name="currency_code"><?php foreach(TUMAN_CURRENCIES as $code=>$label): ?><option value="<?= $code ?>"<?= $values['currency_code']===$code?' selected':'' ?>><?= htmlspecialchars($label.' ('.$code.')',ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><label>Invoice date <input type="date" name="invoice_date" required value="<?= htmlspecialchars($values['invoice_date'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Due date <input type="date" name="due_date" value="<?= htmlspecialchars($values['due_date'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><button>Create draft</button> <a href="/Tuman/teacher/invoices.php">Cancel</a></p></form>
<?php tuman_teacher_page_end(); ?>
