<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php'; require_once __DIR__.'/layout.php'; require_once dirname(__DIR__).'/services/invoices.php';
$current=tuman_require_role('TEACHER');$id=filter_var($_GET['id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id){http_response_code(404);exit('Invoice unavailable.');}$invoice=tuman_teacher_invoice(tuman_database(),$current['id'],(int)$id);if($invoice===null){http_response_code(404);exit('Invoice unavailable.');}$items=tuman_teacher_invoice_items(tuman_database(),$current['id'],(int)$id);$currency=$invoice['currency_code']??'INR';tuman_teacher_page_start('Invoice '.$invoice['invoice_number']);
?>
<h1><?= htmlspecialchars($invoice['invoice_number'],ENT_QUOTES,'UTF-8') ?></h1><p><strong>Status:</strong> <?= htmlspecialchars($invoice['status'],ENT_QUOTES,'UTF-8') ?> · <strong>Currency:</strong> <?= htmlspecialchars($currency,ENT_QUOTES,'UTF-8') ?></p><p><strong>Student:</strong> <?= htmlspecialchars(trim($invoice['first_name'].' '.($invoice['last_name']??'')),ENT_QUOTES,'UTF-8') ?></p><p><strong>Billing period:</strong> <?= htmlspecialchars($invoice['billing_period_from'].' to '.$invoice['billing_period_to'],ENT_QUOTES,'UTF-8') ?></p><div style="overflow-x:auto"><table><thead><tr><th>Description</th><th>Quantity</th><th>Unit rate</th><th>Amount</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><?= htmlspecialchars($item['description'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($item['quantity'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars(tuman_invoice_money_label($item['unit_rate'],$currency),ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars(tuman_invoice_money_label($item['amount'],$currency),ENT_QUOTES,'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div><p><strong>Subtotal:</strong> <?= htmlspecialchars(tuman_invoice_money_label($invoice['subtotal'],$currency),ENT_QUOTES,'UTF-8') ?><br><strong>Discount:</strong> <?= htmlspecialchars(tuman_invoice_money_label($invoice['discount_amount'],$currency),ENT_QUOTES,'UTF-8') ?><br><strong>Total:</strong> <?= htmlspecialchars(tuman_invoice_money_label($invoice['total_amount'],$currency),ENT_QUOTES,'UTF-8') ?></p><?php if($invoice['status']==='DRAFT'): ?><p><a class="button" href="/Tuman/teacher/invoice-issue.php?id=<?= (int)$id ?>">Issue invoice</a> <a href="/Tuman/teacher/invoice-cancel.php?id=<?= (int)$id ?>">Cancel draft</a></p><?php endif; ?><p><a href="/Tuman/teacher/invoices.php">Back to invoices</a></p>
<?php if(($_GET['discount']??'')==='updated'): ?><p>Discount updated successfully.</p><?php endif; ?><?php if(($_GET['email']??'')==='sent'): ?><p>Email sent successfully.</p><?php elseif(($_GET['email']??'')==='failed'): ?><p role="alert">Email could not be sent. Check the SMTP settings and application log.</p><?php elseif(($_GET['email']??'')==='pending'): ?><p>Email is queued because SMTP delivery is disabled.</p><?php endif; ?>
<p><?php if($invoice['status']==='DRAFT'): ?><a class="button" href="/Tuman/teacher/invoice-discount.php?id=<?= (int)$id ?>">Apply discount</a><?php endif; ?> <a class="button" href="/Tuman/teacher/invoice-pdf.php?id=<?= (int)$id ?>">Download invoice PDF</a></p>
<p><a class="button" href="/Tuman/teacher/notification-create.php?id=<?= (int)$id ?>&type=INVOICE">Email invoice</a><?php if(in_array($invoice['status'],['ISSUED','PARTIALLY_PAID'],true)): ?> <a class="button" href="/Tuman/teacher/notification-create.php?id=<?= (int)$id ?>&type=REMINDER">Send reminder</a><?php endif; ?></p>
<?php tuman_teacher_page_end(); ?>
