<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php'; require_once dirname(__DIR__).'/includes/csrf.php'; require_once __DIR__.'/layout.php'; require_once dirname(__DIR__).'/services/messages.php';
$current=tuman_require_role('TEACHER');$db=tuman_database();$error=null;$values=['mode'=>($_GET['mode']??'STUDENT'),'target_id'=>($_GET['target_id']??''),'category'=>'ANNOUNCEMENT','subject'=>'','message_body'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){foreach($values as $key=>$value)$values[$key]=trim((string)($_POST[$key]??$value));try{if(!tuman_csrf_is_valid($_POST['csrf_token']??null))throw new InvalidArgumentException('Your request could not be verified. Please try again.');$message=tuman_message_values($values);$recipients=tuman_message_recipients_for_teacher($db,$current['id'],$values['mode'],$values['target_id']);$attachment=tuman_store_message_attachment($_FILES['attachment']??[]);tuman_send_message($db,$current['id'],$message,$recipients,$attachment);header('Location: /Tuman/teacher/messages.php?sent='.count($recipients));exit;}catch(InvalidArgumentException $e){$error=$e->getMessage();}catch(Throwable $e){error_log('Tuman message send failed: '.$e->getMessage());$error='Unable to send the message right now.';}}
$students=array_filter(tuman_teacher_students($db,$current['id']),fn($s)=>$s['assignment_status']==='ACTIVE');$batches=array_filter(tuman_teacher_batches($db,$current['id']),fn($b)=>$b['status']==='ACTIVE');$messages=tuman_messages_for_recipient($db,$current['id']);tuman_teacher_page_start('Messages');
?>
<h1>Messages</h1><?php if(isset($_GET['sent'])):?><p role="status">Message sent to <?= (int)$_GET['sent'] ?> recipient(s). Their dashboard notification is ready.</p><?php endif;?><?php if($error):?><p role="alert"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p><?php endif;?>
<form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8')?>"><p><label>Send to <select name="mode"><option value="STUDENT"<?=$values['mode']==='STUDENT'?' selected':''?>>One student — choose from Students</option><option value="BATCH"<?=$values['mode']==='BATCH'?' selected':''?>>A batch — choose from Batches</option></select></label></p><p><label>Recipient <select name="target_id" required><option value="">Choose recipient</option><optgroup label="Students under you"><?php foreach($students as $student):?><option value="<?= (int)$student['assignment_id']?>"<?=$values['mode']==='STUDENT'&&$values['target_id']==$student['assignment_id']?' selected':''?>><?=htmlspecialchars(trim($student['first_name'].' '.($student['last_name']??'')),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></optgroup><optgroup label="Batches you are running"><?php foreach($batches as $batch):?><option value="<?= (int)$batch['id']?>"<?=$values['mode']==='BATCH'&&$values['target_id']==$batch['id']?' selected':''?>><?=htmlspecialchars($batch['batch_name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></optgroup></select></label></p><p><label>Category <select name="category"><?php foreach(TUMAN_MESSAGE_CATEGORIES as $category):?><option value="<?=$category?>"<?=$values['category']===$category?' selected':''?>><?=htmlspecialchars(tuman_message_category_label($category),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label></p><p><label>Subject <input name="subject" maxlength="255" required value="<?=htmlspecialchars($values['subject'],ENT_QUOTES,'UTF-8')?>"></label></p><p><label>Message <textarea name="message_body" maxlength="50000" required><?=htmlspecialchars($values['message_body'],ENT_QUOTES,'UTF-8')?></textarea></label></p><p><label>Attachment (optional, one file; PDF, JPG, PNG, DOC, or DOCX; max. 10 MB) <input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"></label></p><p><button>Send message</button></p></form>
<h2>Inbox</h2><?php if($messages===[]):?><p>No messages received.</p><?php else:?><table><thead><tr><th>From</th><th>Category</th><th>Subject</th><th>Received</th><th>Status</th></tr></thead><tbody><?php foreach($messages as $row):?><tr><td><?=htmlspecialchars(trim($row['sender_first_name'].' '.$row['sender_last_name']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_message_category_label($row['category']),ENT_QUOTES,'UTF-8')?></td><td><a href="/Tuman/teacher/message-view.php?id=<?=(int)$row['id']?>"><?=htmlspecialchars($row['subject'],ENT_QUOTES,'UTF-8')?></a></td><td><?=htmlspecialchars($row['created_at'],ENT_QUOTES,'UTF-8')?></td><td><?=$row['read_at']===null?'New':'Read'?></td></tr><?php endforeach;?></tbody></table><?php endif;tuman_teacher_page_end();
