<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php'; require_once __DIR__.'/layout.php'; require_once dirname(__DIR__).'/services/payments.php';
$current=tuman_require_role('TEACHER');$db=tuman_database();
$sql="SELECT p.id,p.invoice_id,i.invoice_number,i.currency_code,sp.first_name,sp.last_name,p.payment_date AS entry_date,p.amount,p.payment_method AS entry_method,p.reference_number,p.status,p.voided_at,'PAYMENT' AS entry_type FROM tmn_payments p INNER JOIN tmn_invoices i ON i.id=p.invoice_id INNER JOIN tmn_teacher_students ts ON ts.id=i.teacher_student_id INNER JOIN tmn_student_profiles sp ON sp.user_id=ts.student_user_id WHERE ts.teacher_user_id=:teacher_id UNION ALL SELECT ca.id,ca.invoice_id,i.invoice_number,i.currency_code,sp.first_name,sp.last_name,DATE(ca.applied_at) AS entry_date,ca.amount,'CREDIT' AS entry_method,CONCAT('Credit #',ca.credit_id) AS reference_number,'APPLIED' AS status,NULL AS voided_at,'CREDIT_APPLICATION' AS entry_type FROM tmn_credit_applications ca INNER JOIN tmn_student_credits c ON c.id=ca.credit_id INNER JOIN tmn_invoices i ON i.id=ca.invoice_id INNER JOIN tmn_teacher_students ts ON ts.id=c.teacher_student_id INNER JOIN tmn_student_profiles sp ON sp.user_id=ts.student_user_id WHERE ts.teacher_user_id=:teacher_id_credits ORDER BY entry_date DESC,id DESC";
$statement=$db->prepare($sql);$statement->execute(['teacher_id'=>$current['id'],'teacher_id_credits'=>$current['id']]);$entries=$statement->fetchAll();tuman_teacher_page_start('Payments');
?>
<h1>Payments</h1><p><a class="button" href="/Tuman/teacher/payment-create.php">Record payment</a></p><p>Credit applications appear here as ledger entries, alongside received payments.</p><div style="overflow-x:auto"><table><thead><tr><th>Type</th><th>Invoice</th><th>Student</th><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($entries as $entry): ?><tr><td><?= $entry['entry_type']==='CREDIT_APPLICATION'?'Credit applied':'Payment received' ?></td><td><?= htmlspecialchars($entry['invoice_number'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars(trim($entry['first_name'].' '.($entry['last_name']??'')),ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($entry['entry_date'],ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars(tuman_invoice_money_label($entry['amount'],$entry['currency_code']),ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars(str_replace('_',' ',$entry['entry_method']),ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($entry['reference_number']??'—',ENT_QUOTES,'UTF-8') ?></td><td><?= htmlspecialchars($entry['status'],ENT_QUOTES,'UTF-8') ?></td><td><?php if($entry['entry_type']==='PAYMENT'&&$entry['status']==='VALID'): ?><a href="/Tuman/teacher/payment-void.php?id=<?= (int)$entry['id'] ?>">Void</a><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php if($entries===[]): ?><p>No payments or credit applications recorded.</p><?php endif; ?>
<?php tuman_teacher_page_end(); ?>
