<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php';
require_once __DIR__.'/layout.php';
require_once dirname(__DIR__).'/services/refunds.php';
$current=tuman_require_role('TEACHER');$db=tuman_database();
$sql="SELECT p.id,p.invoice_id,i.invoice_number,i.currency_code,sp.first_name,sp.last_name,p.payment_date entry_date,p.amount,p.payment_method entry_method,p.reference_number,p.remarks reason,p.status,'PAYMENT' entry_type FROM tmn_payments p INNER JOIN tmn_invoices i ON i.id=p.invoice_id INNER JOIN tmn_teacher_students ts ON ts.id=i.teacher_student_id INNER JOIN tmn_student_profiles sp ON sp.user_id=ts.student_user_id WHERE ts.teacher_user_id=:teacher UNION ALL SELECT c.id,NULL,'—',c.currency_code,sp.first_name,sp.last_name,c.received_date,c.original_amount,c.received_method,c.reference_number,c.remarks,c.status,'ADVANCE' FROM tmn_student_credits c INNER JOIN tmn_teacher_students ts ON ts.id=c.teacher_student_id INNER JOIN tmn_student_profiles sp ON sp.user_id=ts.student_user_id WHERE ts.teacher_user_id=:teacher_advance AND c.source_type='ADVANCE' UNION ALL SELECT ca.id,ca.invoice_id,i.invoice_number,i.currency_code,sp.first_name,sp.last_name,DATE(ca.applied_at),ca.amount,'CREDIT',CONCAT('Credit #',ca.credit_id),NULL,'APPLIED','CREDIT_APPLICATION' FROM tmn_credit_applications ca INNER JOIN tmn_student_credits c ON c.id=ca.credit_id INNER JOIN tmn_invoices i ON i.id=ca.invoice_id INNER JOIN tmn_teacher_students ts ON ts.id=c.teacher_student_id INNER JOIN tmn_student_profiles sp ON sp.user_id=ts.student_user_id WHERE ts.teacher_user_id=:teacher_credit UNION ALL SELECT r.id,r.invoice_id,COALESCE(i.invoice_number,'—'),r.currency_code,sp.first_name,sp.last_name,r.refund_date,r.amount,r.refund_method,r.reference_number,r.reason,'RECORDED',CONCAT('REFUND_',r.refund_type) FROM tmn_refunds r INNER JOIN tmn_teacher_students ts ON ts.id=r.teacher_student_id INNER JOIN tmn_student_profiles sp ON sp.user_id=ts.student_user_id LEFT JOIN tmn_invoices i ON i.id=r.invoice_id WHERE ts.teacher_user_id=:teacher_refund ORDER BY entry_date DESC,id DESC";
$s=$db->prepare($sql);$s->execute(['teacher'=>$current['id'],'teacher_advance'=>$current['id'],'teacher_credit'=>$current['id'],'teacher_refund'=>$current['id']]);$entries=$s->fetchAll();
tuman_teacher_page_start('Payments');
?><h1>Payments and refunds</h1><p><a class="button" href="/Tuman/teacher/payment-create.php">Record payment</a> <a class="button" href="/Tuman/teacher/advance-create.php">Record advance</a> <a class="button" href="/Tuman/teacher/refund-create.php">Record other refund</a></p><p>Every received payment, advance, credit application, and refund is retained in this transaction history.</p><div style="overflow-x:auto"><table><thead><tr><th>Type</th><th>Invoice</th><th>Student</th><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Reason</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($entries as $e):$type=$e['entry_type'];?><tr><td><?=htmlspecialchars($type==='PAYMENT'?'Payment received':($type==='ADVANCE'?'Advance received':($type==='CREDIT_APPLICATION'?'Credit applied':str_replace('_',' ',ucwords(strtolower($type))))),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($e['invoice_number'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(trim($e['first_name'].' '.($e['last_name']??'')),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($e['entry_date'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_invoice_money_label($e['amount'],$e['currency_code']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(str_replace('_',' ',$e['entry_method']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($e['reference_number']??'—',ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($e['reason']??'—',ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($e['status'],ENT_QUOTES,'UTF-8')?></td><td><?php if($type==='PAYMENT'&&$e['status']==='VALID'):?><a href="/Tuman/teacher/payment-refund.php?id=<?=(int)$e['id']?>">Refund</a> · <a href="/Tuman/teacher/payment-void.php?id=<?=(int)$e['id']?>">Void</a><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php if($entries===[]):?><p>No transactions recorded.</p><?php endif;tuman_teacher_page_end();?>
