<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php';require_once __DIR__.'/layout.php';require_once dirname(__DIR__).'/services/reports.php';
$current=tuman_require_role('TEACHER');$db=tuman_database();$error=null;
try{$f=tuman_report_filter($db,$current['id'],$_GET);}catch(InvalidArgumentException $e){$error=$e->getMessage();$f=['from'=>date('Y-m-01'),'to'=>date('Y-m-t'),'assignment_id'=>null];}
$students=tuman_teacher_students($db,$current['id']);$income=tuman_teacher_income_report($db,$current['id'],$f);$outstanding=tuman_teacher_outstanding_report($db,$current['id'],$f);$summaries=tuman_teacher_student_summary($db,$current['id'],$f);
$sql="SELECT p.payment_date entry_date,'Payment received' type,i.invoice_number,sp.first_name,sp.last_name,p.currency_code,p.amount,p.payment_method method,p.reference_number,p.remarks reason FROM tmn_payments p INNER JOIN tmn_invoices i ON i.id=p.invoice_id INNER JOIN tmn_teacher_students ts ON ts.id=i.teacher_student_id INNER JOIN tmn_student_profiles sp ON sp.user_id=ts.student_user_id WHERE ts.teacher_user_id=:teacher AND p.status='VALID' AND p.payment_date BETWEEN :from AND :to";$params=['teacher'=>$current['id'],'from'=>$f['from'],'to'=>$f['to']];if($f['assignment_id']){$sql.=' AND ts.id=:assignment';$params['assignment']=$f['assignment_id'];}$sql.=" UNION ALL SELECT r.refund_date,CONCAT(r.refund_type,' refund'),COALESCE(i.invoice_number,'—'),sp.first_name,sp.last_name,r.currency_code,r.amount,r.refund_method,r.reference_number,r.reason FROM tmn_refunds r INNER JOIN tmn_teacher_students ts ON ts.id=r.teacher_student_id INNER JOIN tmn_student_profiles sp ON sp.user_id=ts.student_user_id LEFT JOIN tmn_invoices i ON i.id=r.invoice_id WHERE ts.teacher_user_id=:refund_teacher AND r.refund_date BETWEEN :refund_from AND :refund_to";$params+=['refund_teacher'=>$current['id'],'refund_from'=>$f['from'],'refund_to'=>$f['to']];if($f['assignment_id']){$sql.=' AND ts.id=:refund_assignment';$params['refund_assignment']=$f['assignment_id'];}$sql.=' ORDER BY entry_date DESC';$st=$db->prepare($sql);$st->execute($params);$ledger=$st->fetchAll();
tuman_teacher_page_start('Reports');
?>
<h1>Reports</h1><p>Review your financial and student activity. Amounts in different currencies remain separate.</p>
<?php if($error):?><p role="alert"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p><?php endif;?>
<form method="get"><p><label>From <input type="date" name="from" value="<?=htmlspecialchars($f['from'],ENT_QUOTES,'UTF-8')?>"></label></p><p><label>To <input type="date" name="to" value="<?=htmlspecialchars($f['to'],ENT_QUOTES,'UTF-8')?>"></label></p><p><label>Student <select name="assignment_id"><option value="">All my students</option><?php foreach($students as $s):?><option value="<?=(int)$s['assignment_id']?>"<?=$f['assignment_id']==$s['assignment_id']?' selected':''?>><?=htmlspecialchars(trim($s['first_name'].' '.($s['last_name']??'')),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label></p><p><button>Apply filters</button> <a class="button" href="/Tuman/teacher/reports.php">Clear</a></p></form>
<h2>Income</h2><div class="cards"><article class="card"><h3>Payments received</h3><p><?=tuman_report_label($income['payments'])?></p></article><article class="card"><h3>Advances received</h3><p><?=tuman_report_label($income['advances'])?></p></article><article class="card"><h3>Refunds</h3><p><?=tuman_report_label($income['refunds'])?></p></article></div><p>Credit applications do not count as new income because the funds were received earlier.</p>
<h3>Payment methods</h3><table><thead><tr><th>Currency</th><th>Method</th><th>Received</th></tr></thead><tbody><?php foreach(array_merge($income['method'],$income['advanceMethods']) as $r):?><tr><td><?=htmlspecialchars($r['currency_code'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(str_replace('_',' ',$r['payment_method']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_invoice_money_label($r['amount'],$r['currency_code']),ENT_QUOTES,'UTF-8')?></td></tr><?php endforeach;?></tbody></table>
<h2>Outstanding balances</h2><?php if($outstanding===[]):?><p>No unpaid invoices match this filter.</p><?php else:?><div style="overflow-x:auto"><table><thead><tr><th>Invoice</th><th>Student</th><th>Period</th><th>Total</th><th>Payments</th><th>Credits</th><th>Refunds</th><th>Outstanding</th><th>Status</th></tr></thead><tbody><?php foreach($outstanding as $i):$due=(tuman_invoice_minor_from_decimal($i['total_amount'])??0)-(tuman_invoice_minor_from_decimal($i['payments'])??0)-(tuman_invoice_minor_from_decimal($i['credits'])??0)+(tuman_invoice_minor_from_decimal($i['refunds'])??0);?><tr><td><a href="/Tuman/teacher/invoice-view.php?id=<?=(int)$i['id']?>"><?=htmlspecialchars($i['invoice_number'],ENT_QUOTES,'UTF-8')?></a></td><td><?=htmlspecialchars(trim($i['first_name'].' '.($i['last_name']??'')),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($i['billing_period_from'].' to '.$i['billing_period_to'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_invoice_money_label($i['total_amount'],$i['currency_code']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_invoice_money_label($i['payments'],$i['currency_code']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_invoice_money_label($i['credits'],$i['currency_code']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_invoice_money_label($i['refunds'],$i['currency_code']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_invoice_money_label(tuman_invoice_decimal_from_minor(max(0,$due)),$i['currency_code']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($i['status'],ENT_QUOTES,'UTF-8')?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<h2>Student summaries</h2><div style="overflow-x:auto"><table><thead><tr><th>Student</th><th>Contact</th><th>Assignment</th><th>Attendance</th><th>Present / absent</th><th>Invoiced / outstanding</th><th>Credits available</th></tr></thead><tbody><?php foreach($summaries as $s):$money=tuman_teacher_student_currency_summary($db,$current['id'],(int)$s['assignment_id'],$f);$creditRows=tuman_report_amounts($db,"SELECT currency_code,SUM(remaining_amount) amount FROM tmn_student_credits WHERE teacher_student_id=:assignment AND status='ACTIVE' GROUP BY currency_code",['assignment'=>$s['assignment_id']]);?><tr><td><a href="/Tuman/teacher/student-view.php?id=<?=(int)$s['assignment_id']?>"><?=htmlspecialchars(trim($s['first_name'].' '.($s['last_name']??'')),ENT_QUOTES,'UTF-8')?></a></td><td><?=htmlspecialchars(($s['email']??'—').' · '.($s['phone']??'—'),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($s['assignment_status'],ENT_QUOTES,'UTF-8')?></td><td><?= (int)$s['attendance_count']?></td><td><?= (int)$s['present_count']?> / <?= (int)$s['absent_count']?></td><td><?=tuman_report_label(array_map(fn($r)=>['currency_code'=>$r['currency_code'],'amount'=>$r['invoiced']],$money))?><br><?=tuman_report_label(array_map(fn($r)=>['currency_code'=>$r['currency_code'],'amount'=>$r['outstanding']],$money))?></td><td><?=tuman_report_label($creditRows)?></td></tr><?php endforeach;?></tbody></table></div>
<h2>Transaction history</h2><?php if($ledger===[]):?><p>No payment or refund transactions match this period.</p><?php else:?><div style="overflow-x:auto"><table><thead><tr><th>Date</th><th>Student</th><th>Type</th><th>Invoice</th><th>Method</th><th>Reference</th><th>Reason</th><th>Amount</th></tr></thead><tbody><?php foreach($ledger as $r):?><tr><td><?=htmlspecialchars($r['entry_date'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(trim($r['first_name'].' '.($r['last_name']??'')),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['type'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['invoice_number'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(str_replace('_',' ',$r['method']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['reference_number']??'—',ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['reason']??'—',ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_invoice_money_label($r['amount'],$r['currency_code']),ENT_QUOTES,'UTF-8')?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php tuman_teacher_page_end();?>
