<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php'; require_once dirname(__DIR__) . '/includes/csrf.php'; require_once __DIR__ . '/layout.php'; require_once dirname(__DIR__) . '/services/responsibilities.php';
$current = tuman_require_role('TEACHER'); $error = null; $students = [];
try { $students = array_filter(tuman_teacher_students(tuman_database(), $current['id']), static fn(array $student): bool => $student['assignment_status'] === 'ACTIVE'); } catch (Throwable $exception) { error_log('Tuman responsibility student selection failed: ' . $exception->getMessage()); $error = 'Students cannot be loaded right now.'; }
$values = ['assignment_id'=>'','responsibility_for'=>'TEACHER','title'=>'','details'=>'','effective_from'=>gmdate('Y-m-d'),'effective_to'=>''];
if ($_SERVER['REQUEST_METHOD'] === 'POST') { foreach ($values as $key => $value) { $values[$key] = trim((string) ($_POST[$key] ?? '')); } if (!tuman_csrf_is_valid($_POST['csrf_token'] ?? null)) { $error = 'Your request could not be verified. Please try again.'; } else { try { tuman_create_responsibility(tuman_database(), $current['id'], tuman_teacher_assignment_id($values['assignment_id']), $values); header('Location: /Tuman/teacher/responsibilities.php?created=1'); exit; } catch (InvalidArgumentException $exception) { $error = $exception->getMessage(); } catch (Throwable $exception) { error_log('Tuman responsibility creation failed: ' . $exception->getMessage()); $error = 'Unable to save the responsibility right now.'; } } }
tuman_teacher_page_start('Add responsibility');
?>
<h1>Add responsibility</h1><p>Responsibilities are recorded for one of your active student relationships.</p><?php if ($error): ?><p role="alert"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p><?php endif; ?><?php if ($students === []): ?><p>You need an active student before adding a responsibility.</p><?php else: ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(), ENT_QUOTES, 'UTF-8') ?>"><p><label>Student <select name="assignment_id" required><option value="">Choose student</option><?php foreach ($students as $student): ?><option value="<?= (int) $student['assignment_id'] ?>"<?= (string) $student['assignment_id'] === $values['assignment_id'] ? ' selected' : '' ?>><?= htmlspecialchars(trim($student['first_name'] . ' ' . ($student['last_name'] ?? '')), ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><label>Responsibility for <select name="responsibility_for"><?php foreach (TUMAN_RESPONSIBILITY_FOR as $for): ?><option value="<?= $for ?>"<?= $for === $values['responsibility_for'] ? ' selected' : '' ?>><?= $for ?></option><?php endforeach; ?></select></label></p><p><label>Title <input name="title" maxlength="200" required value="<?= htmlspecialchars($values['title'], ENT_QUOTES, 'UTF-8') ?>"></label></p><p><label>Details <textarea name="details" rows="4"><?= htmlspecialchars($values['details'], ENT_QUOTES, 'UTF-8') ?></textarea></label></p><p><label>Effective from <input type="date" name="effective_from" required value="<?= htmlspecialchars($values['effective_from'], ENT_QUOTES, 'UTF-8') ?>"></label></p><p><label>Effective to <input type="date" name="effective_to" value="<?= htmlspecialchars($values['effective_to'], ENT_QUOTES, 'UTF-8') ?>"></label></p><p><button type="submit">Save responsibility</button> <a href="/Tuman/teacher/responsibilities.php">Cancel</a></p></form><?php endif; tuman_teacher_page_end(); ?>
