<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php'; require_once dirname(__DIR__) . '/includes/csrf.php'; require_once __DIR__ . '/layout.php'; require_once dirname(__DIR__) . '/services/teacher_students.php';
$current = tuman_require_role('TEACHER'); $error = null;
try { $id = tuman_teacher_assignment_id($_GET['id'] ?? $_POST['id'] ?? null); $student = tuman_teacher_student(tuman_database(), $current['id'], $id); if ($student === null || $student['assignment_status'] !== 'ACTIVE') { throw new InvalidArgumentException(); } } catch (Throwable $exception) { http_response_code(404); tuman_teacher_page_start('Student not found'); echo '<h1>Student not found</h1><p>The requested active student is unavailable.</p>'; tuman_teacher_page_end(); exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') { if (!tuman_csrf_is_valid($_POST['csrf_token'] ?? null)) { $error = 'Your request could not be verified. Please try again.'; } else { try { tuman_deactivate_teacher_student(tuman_database(), $current['id'], $id); header('Location: /Tuman/teacher/students.php?deactivated=1'); exit; } catch (InvalidArgumentException $exception) { $error = 'Student not found.'; } catch (Throwable $exception) { error_log('Tuman student deactivation failed: ' . $exception->getMessage()); $error = 'Unable to deactivate the student right now.'; } } }
tuman_teacher_page_start('Deactivate student assignment');
?>
<h1>Deactivate student assignment</h1><p>You are about to deactivate your assignment with <strong><?= htmlspecialchars(trim($student['first_name'] . ' ' . ($student['last_name'] ?? '')), ENT_QUOTES, 'UTF-8') ?></strong>.</p><p>This prevents the relationship from being treated as active, but preserves the student account and assignment history.</p><?php if ($error): ?><p role="alert"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="id" value="<?= $id ?>"><button type="submit">Confirm deactivation</button> <a href="/Tuman/teacher/students.php">Cancel</a></form>
<?php tuman_teacher_page_end(); ?>
