<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php'; require_once dirname(__DIR__).'/includes/csrf.php'; require_once __DIR__.'/layout.php'; require_once dirname(__DIR__).'/services/teacher_students.php';
$current=tuman_require_role('TEACHER'); $email=''; $error=null; $student=null;
if($_SERVER['REQUEST_METHOD']==='POST') { $email=trim((string)($_POST['email']??'')); $action=(string)($_POST['action']??'preview');
    if(!tuman_csrf_is_valid($_POST['csrf_token']??null)) {$error='Your request could not be verified. Please try again.';}
    elseif($action==='link') { try { tuman_link_existing_student(tuman_database(),$current['id'],$email); header('Location: /Tuman/teacher/students.php?linked=1'); exit; } catch(InvalidArgumentException $e) {$error=$e->getMessage();} catch(Throwable $e) {error_log($e->getMessage());$error='Unable to link the student right now.';} }
    elseif($email===''||filter_var($email,FILTER_VALIDATE_EMAIL)===false) {$error='Enter a valid student email address.';}
    else {$student=tuman_existing_student_profile_for_link(tuman_database(),$email); if($student===null) {$error='This student account cannot be linked.';}}
}
tuman_teacher_page_start('Link existing student');
?>
<h1>Link existing student</h1><p>Find the Student by their Tuman email address, then review their contact profile before creating your own private assignment.</p><?php if($error): ?><p role="alert"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></p><?php endif; ?>
<?php if($student): $address=implode(', ',array_filter([$student['address_line1'],$student['address_line2'],$student['city'],$student['state_name'],$student['postal_code']])); ?><section class="card"><h2><?= htmlspecialchars(trim($student['first_name'].' '.($student['last_name']??'')),ENT_QUOTES,'UTF-8') ?></h2><?php if(!empty($student['photo_path'])): ?><p><img class="profile-photo" src="<?= htmlspecialchars($student['photo_path'],ENT_QUOTES,'UTF-8') ?>" alt="Profile photo"></p><?php endif; ?><p><strong>Email:</strong> <?= htmlspecialchars($student['email'],ENT_QUOTES,'UTF-8') ?></p><p><strong>Phone:</strong> <?= htmlspecialchars($student['phone']??'—',ENT_QUOTES,'UTF-8') ?></p><p><strong>Address:</strong> <?= htmlspecialchars($address?:'—',ENT_QUOTES,'UTF-8') ?></p><p><strong>Guardian:</strong> <?= htmlspecialchars($student['guardian_name']??'—',ENT_QUOTES,'UTF-8') ?><?= !empty($student['guardian_phone'])?' ('.htmlspecialchars($student['guardian_phone'],ENT_QUOTES,'UTF-8').')':'' ?></p><?php if(!empty($student['profile_details'])): ?><p><strong>Profile details:</strong><br><?= nl2br(htmlspecialchars($student['profile_details'],ENT_QUOTES,'UTF-8')) ?></p><?php endif; ?></section><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="email" value="<?= htmlspecialchars($email,ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="action" value="link"><p><button>Confirm link</button> <a href="/Tuman/teacher/student-link.php">Search again</a></p></form>
<?php else: ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="action" value="preview"><p><label>Student email <input type="email" name="email" required value="<?= htmlspecialchars($email,ENT_QUOTES,'UTF-8') ?>"></label></p><p><button>View profile</button> <a href="/Tuman/teacher/students.php">Cancel</a></p></form><?php endif; ?>
<?php tuman_teacher_page_end(); ?>
