<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php'; require_once dirname(__DIR__) . '/includes/csrf.php'; require_once __DIR__ . '/layout.php'; require_once dirname(__DIR__) . '/services/teacher_students.php';
$current=tuman_require_role('TEACHER'); $fields=['username'=>'','email'=>'','first_name'=>'','last_name'=>'','phone'=>'','country_code'=>'']; $error=null;
if ($_SERVER['REQUEST_METHOD']==='POST') { foreach ($fields as $key=>$value) { $fields[$key]=trim((string)($_POST[$key]??'')); } $fields['password']=(string)($_POST['password']??''); if (!tuman_csrf_is_valid($_POST['csrf_token']??null)) { $error='Your request could not be verified. Please try again.'; } else { try { tuman_enrol_student(tuman_database(),$current['id'],$fields); header('Location: /Tuman/teacher/students.php?enrolled=1'); exit; } catch (InvalidArgumentException $e) { $error=$e->getMessage(); } catch (Throwable $e) { error_log($e->getMessage()); $error='Unable to enrol the student right now.'; } } }
tuman_teacher_page_start('Enrol student');
?>
<h1>Enrol student</h1><?php if ($error): ?><p role="alert"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><p><label>First name <input name="first_name" required value="<?= htmlspecialchars($fields['first_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Last name <input name="last_name" value="<?= htmlspecialchars($fields['last_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Username <input name="username" required value="<?= htmlspecialchars($fields['username'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Temporary password <input type="password" name="password" minlength="12" required></label></p><p><label>Email <input type="email" name="email" value="<?= htmlspecialchars($fields['email'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Phone <input name="phone" value="<?= htmlspecialchars($fields['phone'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Country <select name="country_code"><option value="">Not specified</option><?php foreach(TUMAN_COUNTRIES as $code=>$name): ?><option value="<?= $code ?>"<?= $fields['country_code']===$code?' selected':'' ?>><?= htmlspecialchars($name.' ('.$code.')',ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><button>Enrol student</button> <a href="/Tuman/teacher/students.php">Cancel</a></p></form>
<?php tuman_teacher_page_end(); ?>
