<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php'; require_once dirname(__DIR__).'/includes/csrf.php'; require_once __DIR__.'/layout.php'; require_once dirname(__DIR__).'/services/teacher_students.php';
$current=tuman_require_role('TEACHER');$error=null;
try{$id=tuman_teacher_assignment_id($_GET['id']??$_POST['id']??null);$student=tuman_teacher_student(tuman_database(),$current['id'],$id);if($student===null){throw new InvalidArgumentException();}}catch(Throwable $e){http_response_code(404);tuman_teacher_page_start('Student not found');echo '<h1>Student not found</h1><p>The requested student is unavailable.</p>';tuman_teacher_page_end();exit;}
$fields=['first_name','last_name','email','phone','address_line1','address_line2','city','state_name','postal_code','country_code','guardian_name','guardian_phone','profile_details','effective_from','assignment_status'];$student['effective_from']=$student['start_date'];foreach($fields as $field){$student[$field]=$student[$field]??'';}
if($_SERVER['REQUEST_METHOD']==='POST'){foreach($fields as $field){$student[$field]=trim((string)($_POST[$field]??''));}if(!tuman_csrf_is_valid($_POST['csrf_token']??null)){$error='Your request could not be verified. Please try again.';}else{try{tuman_update_teacher_student(tuman_database(),$current['id'],$id,$student);header('Location: /Tuman/teacher/student-view.php?id='.$id);exit;}catch(InvalidArgumentException $e){$error=$e->getMessage();}catch(Throwable $e){error_log($e->getMessage());$error='Unable to update the student right now.';}}}
tuman_teacher_page_start('Edit student');
?>
<h1>Edit student profile</h1><?php if($error): ?><p role="alert"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><input type="hidden" name="id" value="<?= $id ?>"><p><label>Effective from <input type="date" name="effective_from" max="<?= gmdate('Y-m-d') ?>" required value="<?= htmlspecialchars($student['effective_from'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Assignment status <select name="assignment_status"><?php foreach(['ACTIVE','INACTIVE'] as $status): ?><option value="<?= $status ?>"<?= $status===$student['assignment_status']?' selected':'' ?>><?= $status ?></option><?php endforeach; ?></select></label></p><p><label>First name <input name="first_name" required value="<?= htmlspecialchars($student['first_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Last name <input name="last_name" value="<?= htmlspecialchars($student['last_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Email <input type="email" name="email" value="<?= htmlspecialchars($student['email'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Phone <input name="phone" value="<?= htmlspecialchars($student['phone'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Country <select name="country_code"><option value="">Not specified</option><?php foreach(TUMAN_COUNTRIES as $code=>$name): ?><option value="<?= $code ?>"<?= $code===$student['country_code']?' selected':'' ?>><?= htmlspecialchars($name.' ('.$code.')',ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></label></p><p><label>Guardian name <input name="guardian_name" value="<?= htmlspecialchars($student['guardian_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Guardian phone <input name="guardian_phone" value="<?= htmlspecialchars($student['guardian_phone'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Address <input name="address_line1" value="<?= htmlspecialchars($student['address_line1'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Address line 2 <input name="address_line2" value="<?= htmlspecialchars($student['address_line2'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>City <input name="city" value="<?= htmlspecialchars($student['city'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>State <input name="state_name" value="<?= htmlspecialchars($student['state_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Postal code <input name="postal_code" value="<?= htmlspecialchars($student['postal_code'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Profile details <textarea name="profile_details" maxlength="5000"><?= htmlspecialchars($student['profile_details'],ENT_QUOTES,'UTF-8') ?></textarea></label></p><p><button>Save changes</button> <a href="/Tuman/teacher/student-view.php?id=<?= $id ?>">Cancel</a></p></form>
<?php tuman_teacher_page_end(); ?>
