<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once __DIR__ . '/payments.php';
use Dompdf\Dompdf;

function tuman_teacher_payment_details(PDO $db,int $teacherId): array { $s=$db->prepare('SELECT * FROM tmn_teacher_payment_details WHERE teacher_user_id=:id');$s->execute(['id'=>$teacherId]);return $s->fetch()?:[]; }
function tuman_save_teacher_payment_details(PDO $db,int $teacherId,array $input): void { $columns=['indian_account_holder','indian_bank_name','indian_branch','indian_account_number','indian_ifsc','indian_upi_id','indian_pan_gstin','indian_reference_note','international_beneficiary','international_bank_name','international_bank_address','international_account_iban','international_swift_bic','international_intermediary_details','international_fee_note','international_reference_note'];$values=[];foreach($columns as $column){$value=trim((string)($input[$column]??''));if(strlen($value)>500){throw new InvalidArgumentException('A payment detail is too long.');}$values[$column]=$value===''?null:$value;}$sql='INSERT INTO tmn_teacher_payment_details (teacher_user_id,'.implode(',',$columns).') VALUES (:teacher_user_id,:'.implode(',:',$columns).') ON DUPLICATE KEY UPDATE ';$updates=[];foreach($columns as $column){$updates[]="$column=VALUES($column)";}$s=$db->prepare($sql.implode(',',$updates));$s->execute(['teacher_user_id'=>$teacherId]+$values); }
function tuman_pdf_payment_instructions(array $details,string $currency): string { $prefix=$currency==='INR'?'indian_':'international_';$labels=$currency==='INR'?['account_holder'=>'Account holder','bank_name'=>'Bank','branch'=>'Branch','account_number'=>'Account number','ifsc'=>'IFSC','upi_id'=>'UPI ID','pan_gstin'=>'PAN/GSTIN','reference_note'=>'Payment reference']:['beneficiary'=>'Beneficiary','bank_name'=>'Bank','bank_address'=>'Bank address','account_iban'=>'Account/IBAN','swift_bic'=>'SWIFT/BIC','intermediary_details'=>'Intermediary bank','fee_note'=>'Transfer fees','reference_note'=>'Payment reference'];$html='<h2>Payment instructions</h2><table>';foreach($labels as $key=>$label){$value=$details[$prefix.$key]??null;if($value!==null&&$value!==''){$html.='<tr><th>'.htmlspecialchars($label).'</th><td>'.nl2br(htmlspecialchars($value)).'</td></tr>';}}return $html.'</table>'; }
function tuman_stream_invoice_pdf(PDO $db,int $teacherId,int $invoiceId): void { $invoice=tuman_teacher_invoice($db,$teacherId,$invoiceId);if($invoice===null){http_response_code(404);exit('Invoice unavailable.');}$items=tuman_teacher_invoice_items($db,$teacherId,$invoiceId);$currency=$invoice['currency_code'];$rows='';foreach($items as $item){$rows.='<tr><td>'.htmlspecialchars($item['description']).'</td><td>'.htmlspecialchars($item['quantity']).'</td><td>'.tuman_invoice_money_label($item['amount'],$currency).'</td></tr>';}$address=array_filter([$invoice['address_line1'],$invoice['address_line2'],$invoice['city'],$invoice['state_name'],$invoice['postal_code'],$invoice['country_code']]);$issuedTo=htmlspecialchars(trim($invoice['first_name'].' '.($invoice['last_name']??''))).'<br>'.nl2br(htmlspecialchars(implode(', ', $address)));$html='<html><style>body{font-family:DejaVu Sans;color:#172033}h1{color:#12345b}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ccd6e0;text-align:left}th{background:#edf3fa}</style><body><h1>Invoice '.$invoice['invoice_number'].'</h1><p><strong>Issued to:</strong><br>'.$issuedTo.'</p><p>Status: '.$invoice['status'].' | Currency: '.$currency.'</p><p>Billing period: '.$invoice['billing_period_from'].' to '.$invoice['billing_period_to'].'</p><table><tr><th>Description</th><th>Quantity</th><th>Amount</th></tr>'.$rows.'</table><h2>Total: '.tuman_invoice_money_label($invoice['total_amount'],$currency).'</h2>'.tuman_pdf_payment_instructions(tuman_teacher_payment_details($db,$teacherId),$currency).'</body></html>';$pdf=new Dompdf();$pdf->loadHtml($html);$pdf->setPaper('A4');$pdf->render();$pdf->stream($invoice['invoice_number'].'.pdf',['Attachment'=>true]); }
function tuman_stream_receipt_pdf(PDO $db,int $teacherId,int $paymentId): void { $payment=tuman_teacher_payment($db,$teacherId,$paymentId);if($payment===null||$payment['status']!=='VALID'){http_response_code(404);exit('Receipt unavailable.');}$html='<html><body><h1>Payment receipt</h1><p>Invoice: '.htmlspecialchars($payment['invoice_number']).'</p><p>Date: '.htmlspecialchars($payment['payment_date']).'</p><p>Amount: '.htmlspecialchars(tuman_invoice_money_label($payment['amount'],$payment['currency_code'])).'</p><p>Method: '.htmlspecialchars($payment['payment_method']).'</p></body></html>';$pdf=new Dompdf();$pdf->loadHtml($html);$pdf->setPaper('A4');$pdf->render();$pdf->stream('receipt-'.$paymentId.'.pdf',['Attachment'=>true]); }
