<?php
declare(strict_types=1);
require_once __DIR__.'/credits.php';
require_once __DIR__.'/teacher_students.php';

function tuman_refund_values(array $input,bool $reasonRequired=true): array { $v=tuman_payment_values($input);$reason=trim((string)($input['reason']??$input['remarks']??''));if($reasonRequired&&$reason==='')throw new InvalidArgumentException('Enter the reason for this refund.');if(strlen($reason)>500)throw new InvalidArgumentException('The refund reason is too long.');$v['reason']=$reason;return $v; }
function tuman_insert_refund(PDO $db,array $r,array $v): int { $s=$db->prepare('INSERT INTO tmn_refunds (teacher_student_id,invoice_id,payment_id,credit_id,refund_type,refund_date,amount,currency_code,refund_method,reference_number,reason) VALUES (:assignment,:invoice,:payment,:credit,:type,:date,:amount,:currency,:method,:reference,:reason)');$s->execute(['assignment'=>$r['assignment_id'],'invoice'=>$r['invoice_id']??null,'payment'=>$r['payment_id']??null,'credit'=>$r['credit_id']??null,'type'=>$r['type'],'date'=>$v['payment_date'],'amount'=>$v['amount'],'currency'=>$r['currency_code'],'method'=>$v['payment_method'],'reference'=>$v['reference_number'],'reason'=>$v['reason']]);return (int)$db->lastInsertId(); }
function tuman_refund_payment(PDO $db,int $teacherId,int $paymentId,array $input): void { $v=tuman_refund_values($input);$db->beginTransaction();try{$p=tuman_teacher_payment($db,$teacherId,$paymentId);if($p===null||$p['status']!=='VALID')throw new InvalidArgumentException('Payment is unavailable.');$invoice=tuman_locked_teacher_invoice($db,$teacherId,(int)$p['invoice_id']);$credit=$db->prepare('SELECT COALESCE(SUM(original_amount),0) FROM tmn_student_credits WHERE source_payment_id=:id FOR UPDATE');$credit->execute(['id'=>$paymentId]);$creditMinor=tuman_invoice_minor_from_decimal((string)$credit->fetchColumn())??0;$previous=$db->prepare("SELECT COALESCE(SUM(amount),0) FROM tmn_refunds WHERE payment_id=:id AND refund_type='PAYMENT' FOR UPDATE");$previous->execute(['id'=>$paymentId]);$available=(tuman_invoice_minor_from_decimal($p['amount'])??0)-$creditMinor-(tuman_invoice_minor_from_decimal((string)$previous->fetchColumn())??0);if($v['amount_minor']>$available)throw new InvalidArgumentException('Refund cannot exceed the unrefunded amount of this payment.');$id=tuman_insert_refund($db,['assignment_id'=>$invoice['teacher_student_id'],'invoice_id'=>$invoice['id'],'payment_id'=>$paymentId,'type'=>'PAYMENT','currency_code'=>$p['currency_code']],$v);$paid=tuman_invoice_valid_payment_minor($db,(int)$invoice['id'],$p['currency_code']);tuman_update_invoice_payment_status($db,$teacherId,$invoice,$paid);tuman_log_activity($db,$teacherId,'PAYMENT_REFUNDED','REFUND',$id,['payment_id'=>$paymentId,'invoice_number'=>$p['invoice_number'],'amount'=>$v['amount'],'currency_code'=>$p['currency_code'],'reason'=>$v['reason']]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;} }
function tuman_refund_credit(PDO $db,int $teacherId,int $creditId,array $input): void { $v=tuman_refund_values($input);$db->beginTransaction();try{$c=tuman_teacher_credit($db,$teacherId,$creditId);if($c===null||$c['status']!=='ACTIVE'||$v['amount_minor']>(tuman_invoice_minor_from_decimal($c['remaining_amount'])??0))throw new InvalidArgumentException('Refund cannot exceed the unused credit.');$id=tuman_insert_refund($db,['assignment_id'=>$c['teacher_student_id'],'credit_id'=>$creditId,'type'=>'CREDIT','currency_code'=>$c['currency_code']],$v);$left=(tuman_invoice_minor_from_decimal($c['remaining_amount'])??0)-$v['amount_minor'];$db->prepare('UPDATE tmn_student_credits SET remaining_amount=:amount,status=:status WHERE id=:id')->execute(['amount'=>tuman_invoice_decimal_from_minor($left),'status'=>$left===0?'EXHAUSTED':'ACTIVE','id'=>$creditId]);tuman_log_activity($db,$teacherId,'CREDIT_REFUNDED','REFUND',$id,['credit_id'=>$creditId,'amount'=>$v['amount'],'currency_code'=>$c['currency_code'],'reason'=>$v['reason']]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;} }
function tuman_record_adjustment_refund(PDO $db,int $teacherId,int $assignmentId,array $input): void { $v=tuman_refund_values($input);$currency=tuman_currency_code((string)($input['currency_code']??''));if($currency===null)throw new InvalidArgumentException('Choose a supported currency.');$student=tuman_teacher_student($db,$teacherId,$assignmentId);if($student===null)throw new InvalidArgumentException('Student is unavailable.');$id=tuman_insert_refund($db,['assignment_id'=>$assignmentId,'type'=>'ADJUSTMENT','currency_code'=>$currency],$v);tuman_log_activity($db,$teacherId,'ADJUSTMENT_REFUND_RECORDED','REFUND',$id,['amount'=>$v['amount'],'currency_code'=>$currency,'reason'=>$v['reason']]); }
