<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php'; require_once dirname(__DIR__).'/includes/csrf.php'; require_once __DIR__.'/layout.php'; require_once dirname(__DIR__).'/services/messages.php'; require_once dirname(__DIR__).'/services/student_portal.php';
$current=tuman_require_role('STUDENT');$db=tuman_database();$error=null;$values=['assignment_id'=>'','category'=>'OFFICIAL','subject'=>'','message_body'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){foreach($values as $key=>$value)$values[$key]=trim((string)($_POST[$key]??$value));try{if(!tuman_csrf_is_valid($_POST['csrf_token']??null))throw new InvalidArgumentException('Your request could not be verified. Please try again.');$message=tuman_message_values($values);$recipients=tuman_message_recipients_for_student($db,$current['id'],$values['assignment_id']);$attachment=tuman_store_message_attachment($_FILES['attachment']??[]);tuman_send_message($db,$current['id'],$message,$recipients,$attachment);header('Location: /Tuman/student/messages.php?sent=1');exit;}catch(InvalidArgumentException $e){$error=$e->getMessage();}catch(Throwable $e){error_log('Tuman message send failed: '.$e->getMessage());$error='Unable to send the message right now.';}}
$teachers=array_filter(tuman_student_teacher_assignments($db,$current['id']),fn($t)=>($t['assignment_status']??'ACTIVE')==='ACTIVE');$messages=tuman_messages_for_recipient($db,$current['id']);tuman_student_page_start('Messages');
?>
<h1>Messages</h1><?php if(isset($_GET['sent'])):?><p role="status">Message sent. Your teacher has been notified.</p><?php endif;?><?php if($error):?><p role="alert"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></p><?php endif;?>
<form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="category" value="OFFICIAL"><p><label>Teacher <select name="assignment_id" required><option value="">Choose teacher</option><?php foreach($teachers as $teacher):?><option value="<?= (int)$teacher['assignment_id']?>"<?=$values['assignment_id']==$teacher['assignment_id']?' selected':''?>><?=htmlspecialchars(trim($teacher['first_name'].' '.($teacher['last_name']??'')),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label></p><p><label>Subject <input name="subject" maxlength="255" required value="<?=htmlspecialchars($values['subject'],ENT_QUOTES,'UTF-8')?>"></label></p><p><label>Message <textarea name="message_body" maxlength="50000" required><?=htmlspecialchars($values['message_body'],ENT_QUOTES,'UTF-8')?></textarea></label></p><p><label>Attachment (optional, one file; PDF, JPG, PNG, DOC, or DOCX; max. 10 MB) <input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"></label></p><p><button>Send message</button></p></form>
<h2>Inbox</h2><?php if($messages===[]):?><p>No messages received.</p><?php else:?><table><thead><tr><th>From</th><th>Category</th><th>Subject</th><th>Received</th><th>Status</th></tr></thead><tbody><?php foreach($messages as $row):?><tr><td><?=htmlspecialchars(trim($row['sender_first_name'].' '.$row['sender_last_name']),ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars(tuman_message_category_label($row['category']),ENT_QUOTES,'UTF-8')?></td><td><a href="/Tuman/student/message-view.php?id=<?=(int)$row['id']?>"><?=htmlspecialchars($row['subject'],ENT_QUOTES,'UTF-8')?></a></td><td><?=htmlspecialchars($row['created_at'],ENT_QUOTES,'UTF-8')?></td><td><?=$row['read_at']===null?'New':'Read'?></td></tr><?php endforeach;?></tbody></table><?php endif;tuman_student_page_end();
