<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/includes/auth.php'; require_once dirname(__DIR__).'/includes/csrf.php'; require_once __DIR__.'/layout.php'; require_once dirname(__DIR__).'/services/profiles.php';
$current=tuman_require_role('ADMIN'); $db=tuman_database(); $error=null; $profile=tuman_profile($db,$current['id'],'ADMIN');
if($_SERVER['REQUEST_METHOD']==='POST') { if(!tuman_csrf_is_valid($_POST['csrf_token']??null)) {$error='Your request could not be verified. Please try again.';} else {try {tuman_save_profile($db,$current['id'],'ADMIN',$_POST,$_FILES['photo']??[]);header('Location: /Tuman/admin/profile.php?updated=1');exit;} catch(InvalidArgumentException $e) {$error=$e->getMessage();} catch(Throwable $e) {error_log($e->getMessage());$error='Unable to update your profile right now.';}} $profile=array_merge($profile??[],$_POST); }
foreach(['first_name','last_name','email','phone','address_line1','address_line2','city','state_name','postal_code','profile_details'] as $field){$profile[$field]=$profile[$field]??'';} tuman_admin_page_start('My profile');
?>
<h1>My profile</h1><?php if(isset($_GET['updated'])): ?><p>Your profile has been updated.</p><?php endif; ?><?php if($error): ?><p role="alert"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?></p><?php endif; ?><?php if(!empty($profile['photo_path'])): ?><p><img class="profile-photo" src="<?= htmlspecialchars($profile['photo_path'],ENT_QUOTES,'UTF-8') ?>" alt="Your profile photo"></p><?php endif; ?><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(),ENT_QUOTES,'UTF-8') ?>"><p><label>First name <input name="first_name" required value="<?= htmlspecialchars($profile['first_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Last name <input name="last_name" value="<?= htmlspecialchars($profile['last_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Email <input type="email" name="email" value="<?= htmlspecialchars($profile['email'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Telephone <input name="phone" value="<?= htmlspecialchars($profile['phone'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Address <input name="address_line1" value="<?= htmlspecialchars($profile['address_line1'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Address line 2 <input name="address_line2" value="<?= htmlspecialchars($profile['address_line2'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>City <input name="city" value="<?= htmlspecialchars($profile['city'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>State/area <input name="state_name" value="<?= htmlspecialchars($profile['state_name'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Postal code <input name="postal_code" value="<?= htmlspecialchars($profile['postal_code'],ENT_QUOTES,'UTF-8') ?>"></label></p><p><label>Profile details <textarea name="profile_details" maxlength="5000"><?= htmlspecialchars($profile['profile_details'],ENT_QUOTES,'UTF-8') ?></textarea></label></p><p><label>Profile photo <input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label></p><p><button>Save profile</button></p></form>
<?php tuman_admin_page_end(); ?>
