<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php'; require_once dirname(__DIR__) . '/includes/csrf.php'; require_once __DIR__ . '/layout.php'; require_once dirname(__DIR__) . '/services/admin_users.php';
$current = tuman_require_role('ADMIN'); $error = null;
try { $id = tuman_admin_user_id($_GET['id'] ?? $_POST['id'] ?? null); $user = tuman_admin_user(tuman_database(), $id); if ($user === null) { throw new InvalidArgumentException('User not found.'); } } catch (Throwable $exception) { http_response_code(404); tuman_admin_page_start('User not found'); echo '<h1>User not found</h1><p>The requested user is unavailable.</p>'; tuman_admin_page_end(); exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') { if (!tuman_csrf_is_valid($_POST['csrf_token'] ?? null)) { $error = 'Your request could not be verified. Please try again.'; } else { try { tuman_admin_reset_password(tuman_database(), $current['id'], $id, (string) ($_POST['password'] ?? ''), (string) ($_POST['password_confirmation'] ?? '')); header('Location: /Tuman/admin/users.php?password=1'); exit; } catch (InvalidArgumentException $exception) { $error = $exception->getMessage(); } catch (Throwable $exception) { error_log('Tuman password reset failed: ' . $exception->getMessage()); $error = 'Unable to reset the password right now.'; } } }
tuman_admin_page_start('Reset password');
?>
<h1>Reset password</h1><p>Set a new password for <strong><?= htmlspecialchars($user['username'], ENT_QUOTES, 'UTF-8') ?></strong>. The password is not displayed or stored in plain text.</p><?php if ($error): ?><p role="alert"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="id" value="<?= $id ?>"><p><label>New password <input type="password" name="password" minlength="12" required autocomplete="new-password"></label></p><p><label>Confirm password <input type="password" name="password_confirmation" minlength="12" required autocomplete="new-password"></label></p><p><button type="submit">Reset password</button> <a href="/Tuman/admin/users.php">Cancel</a></p></form>
<?php tuman_admin_page_end(); ?>
