<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/includes/auth.php'; require_once dirname(__DIR__) . '/includes/csrf.php'; require_once __DIR__ . '/layout.php'; require_once dirname(__DIR__) . '/services/admin_users.php';
$current = tuman_require_role('ADMIN'); $error = null;
try { $id = tuman_admin_user_id($_GET['id'] ?? null); $user = tuman_admin_user(tuman_database(), $id); if ($user === null) { throw new InvalidArgumentException('User not found.'); } } catch (Throwable $exception) { http_response_code(404); tuman_admin_page_start('User not found'); echo '<h1>User not found</h1><p>The requested user is unavailable.</p>'; tuman_admin_page_end(); exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') { $user['username'] = trim((string) ($_POST['username'] ?? '')); $user['email'] = trim((string) ($_POST['email'] ?? '')); $user['role'] = (string) ($_POST['role'] ?? ''); if (!tuman_csrf_is_valid($_POST['csrf_token'] ?? null)) { $error = 'Your request could not be verified. Please try again.'; } else { try { tuman_admin_update_user(tuman_database(), $current['id'], $id, $user['username'], $user['email'], $user['role']); header('Location: /Tuman/admin/users.php?updated=1'); exit; } catch (InvalidArgumentException $exception) { $error = $exception->getMessage(); } catch (Throwable $exception) { error_log('Tuman user update failed: ' . $exception->getMessage()); $error = 'Unable to update the user right now.'; } } }
tuman_admin_page_start('Edit user');
?>
<h1>Edit user</h1><?php if ($error): ?><p role="alert"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(tuman_csrf_token(), ENT_QUOTES, 'UTF-8') ?>"><p><label>Username <input name="username" maxlength="50" required value="<?= htmlspecialchars($user['username'], ENT_QUOTES, 'UTF-8') ?>"></label></p><p><label>Email <input type="email" name="email" maxlength="254" value="<?= htmlspecialchars($user['email'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></label></p><p><label>Role <select name="role"><?php foreach (TUMAN_ROLES as $role): ?><option value="<?= $role ?>"<?= $role === $user['role'] ? ' selected' : '' ?>><?= $role ?></option><?php endforeach; ?></select></label></p><p><button type="submit">Save changes</button> <a href="/Tuman/admin/users.php">Cancel</a></p></form><p><a href="/Tuman/admin/user-password.php?id=<?= $id ?>">Reset this user’s password</a> · <a href="/Tuman/admin/user-status.php?id=<?= $id ?>">Change account status</a></p>
<?php tuman_admin_page_end(); ?>
